### ISSUE TITLE
User Management Testing

### ISSUE THREAD

**Issue by YashKumarVerma** [LockedUp-Coders/nostalgify#39]
Tests need to be written for each of the route that has been created. 

---
- [ ] Test User Registration :green_circle:  : @vivekshah1801 
- [ ] Test User Login :green_circle: 
- [ ] Test User Logout :green_circle: 
- [ ] Test User Profile Viewing :green_circle: 
- [ ] Test User Profile Updation :green_circle: @harshil15999 

---
Tests must 
- aim 100% coverage on the following routes. 
- include cases when one of the object is not passed, for all objects.

---
How to work on this.
- Pick one of the above
- Open issue with title : `New test proposal: <test name>`
- Open issue only when the PR to write that module is complete. (i.e. you cannot write tests if route doesn't exist, in theory you can, but let's not make it complex)
- Then tag me (@YashKumarVerma)
- When I assign it to you, and then you can start working on it.

---
Read up about  JEST / Mocha

---
:green_circle:  Easy
:yellow_circle: Moderate
:red_circle: Tough

**Comment by YashKumarVerma** [comment]
@vivekshah1801  this is put on hold.

**Comment by vivekshah1801** [comment]
Ok

**Comment by YashKumarVerma** [comment]
@vivekshah1801  you can continue now.
