### ISSUE TITLE
Organization Module : Tests

### ISSUE THREAD

**Issue by YashKumarVerma** [LockedUp-Coders/nostalgify#49]
Write tests for the following routes
- [ ] :green_circle: `GET /org/:orgUsername` get details of the organization 
- [ ] :green_circle:  `POST /org/:orgUsername/create` Create new Org, can be done only by someone who's a user, which later becomes the admin of the org.
- [ ] :green_circle:  `PUT /org/:orgUsername/update` Edit the details of the org.
- [ ] :green_circle:  `DELETE /org/:orgUsername` delete the organization

 

How to work on this.
- Pick one of the above
- Open issue with title : `New Test proposal: Org : <page name>`
- Describe how you are going to solve it (short points, not a theory exam here)
- Then tag me (@YashKumarVerma)
- When I assign it to you, and then you can start working on it.

Make sure that you add the text "**Child of #49**" in the issue body so that it is linked to this issue.  

The number of issues that are still available to be claimed is equal to the number items listed above without a username
